### ISSUE TITLE
Please add me

### ISSUE THREAD

**Issue by mike7seven** [Denhac/help-i-am-not-an-org-member#2]
Please add me.

**Comment by funkmasterflex** [comment]
Please take me off this list

Joe Miyaki
c. 303.519.1343

"We can, by speech and pen, make men [and women] more enlightened and
better" - Voltaire

On Apr 27, 2017 2:15 PM, "mike7seven" <notifications@github.com> wrote:

Please add me.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Denhac/help-i-am-not-an-org-member/issues/2>, or mute
the thread

**Comment by Jnesselr** [comment]
You can unsubscribe from the thread or repository yourself. Please don't add onto another issue that someone has asked about. I've removed you from the DenHac Github organization.

**Comment by Jnesselr** [comment]
@mike7seven you have been added to the DenHac organization.
